name: autofix.ci

on:
  pull_request:
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup Bun
        uses: oven-sh/setup-bun@2b176a6e02983d9ed668db3c687439eb49fe611a
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Format code
        run: bun format .
      - name: Run autofix
        uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
