name: Code quality

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup Bun
        uses: oven-sh/setup-bun@2b176a6e02983d9ed668db3c687439eb49fe611a
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run code quality checks
        run: bun ci:check
